Small fixes for imap service, filter with from-date and decoding
lawik/imap-email-address-collector pull request #1
Opened 2019-10-02 08:52 UTC by elliotjon

2019-10-02 11:35 UTC, lawik requested changes
Ser skitbra ut. Bara några småsaker.

2019-10-02 11:35 UTC, lawik commented on README.md
> +	  --port PORT			(optional) imap host port, defaults to 993
Formatterade du om spacingen här? Verkar lite onödigt. Gissar på formateraren. Eller missar jag något.

2019-10-02 11:35 UTC, lawik commented on README.md
> +	  --fromdate DD-MM-YYYY 	(optional) filter out older than date
Jag har inte lagt till --skip här, det får du gärna göra.

2019-10-02 11:35 UTC, lawik commented on imap-email-address-collector.py
> +	if name.startswith('=?', 0):
Funkar decode_header även om den inte har `=?` i sig?
För om det finns några andra cases som kan strula så är nog decode_header önskvärt för all text. Men förstås bara om det funkar :)

2019-10-03 11:28 UTC, elliotjon commented
Something is still weird with this script. When running with --fromdate and for example the last two years all works fine. But when running script without fromdate the csv-file doesn't have 'åäö'. I don't know whats causing this yet.

2019-10-04 06:15 UTC, merged